# Example configuration for VSD dataset with normalization
dataset: "vsd"
vsd_hdf5_path: "G:\\My Drive\\HDF5_DATA_AFTER_PREPROCESSING2\\vsd_video_data.hdf5"

# DataLoader settings
batch_size: 4
num_workers: 2
shuffle: true

# Frame slicing configuration
frame_start: 0          # Start frame index (0-based)
frame_end: 255          # End frame index (inclusive), None for all frames

# Normalization settings
normalize: true
normalization_type: "baseline_zscore"  # Options: "baseline_zscore", "baseline_robust"
baseline_frame: 20                     # Frame to use as baseline (default: 20)
cache_dir: "cache"                     # Directory for caching normalization statistics

# Additional normalization parameters
normalization_kwargs:
  epsilon: 1e-8                        # Small value to avoid division by zero

# Alternative configurations:

# Example 1: Baseline Z-score normalization
baseline_zscore_config:
  normalize: true
  normalization_type: "baseline_zscore"
  baseline_frame: 20
  frame_start: 10
  frame_end: 100
  normalization_kwargs:
    epsilon: 1e-8

# Example 2: Baseline Robust normalization
baseline_robust_config:
  normalize: true
  normalization_type: "baseline_robust"
  baseline_frame: 15
  frame_start: 5
  frame_end: 50
  normalization_kwargs:
    epsilon: 1e-8

# Example 3: No normalization (original behavior)
no_normalization_config:
  normalize: false
  frame_start: 0
  frame_end: 255

# Example 4: Different baseline frame
custom_baseline_config:
  normalize: true
  normalization_type: "baseline_zscore"
  baseline_frame: 30
  frame_start: 0
  frame_end: 100
